spring:
  application:
    name: bookbook

  profiles:
    active: dev

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /api/docs
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api/docs-json