spring.application.name=exercise1
server.port=8081

spring.jwt.signerkey=${JWT_SIGNER_KEY:1/2cbirKp5GdXGj/SYm4HDC3DEyOlCQO+WC7IfwATE8dyU4+GdQzQx8Dx1Tjc7a/}

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/sparkminds-e1
spring.datasource.username=${POSTGRES_USER:app_user}
spring.datasource.password=${POSTGRES_PASSWORD:12345}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis Config
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:12345}
spring.data.redis.timeout=60000

# MAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME:heulwentech@gmail.com}
spring.mail.password=${EMAIL_PASSWORD:rlmr unqo famc fhnu}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Google Client
google.client.id=${GOOGLE_CLIENT:415209795379-fdvdvu59mam6itn486t81u150f8egc76}.apps.googleusercontent.com

# Folder Upload
file.upload-dir=uploads/books